### ISSUE TITLE
Update the chips disabled state

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/wl-hopper#260]
**COS:** 

- Disabled should be removed from the variant, and change to a isDisabled property
- add `data-disabled` and `aria-disabled` to the element when isDisabled is true
- Add in the documentation that there is a disabled property available, but this property is only expected when the containing control is disabled, and is not meant to be used as a standalone chip

**Comment by vicky-comeau** [comment]
This is being done as part of the merging of Chip and Tag
