### ISSUE TITLE
Standardize the className, style and children props. 

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/wl-hopper#278]
All RAC components allows className, style and children to be function, where the parameters are the component's state, and the return value the className to append. 
```
<Checkbox className={({isDisabled}) => isDisabled ? "disabled" : "enabled" />
```

However, some of our component that are not based on react aria do not allow such function, such as the Chip component. 
We should make sure that all component with a state (not the stylistic stuff like variant/fluid/size) should allow those functions

**Comment by alexasselin008** [comment]
For instance, the Avatar, or basically any component extending BaseComponent, aka not RAC component, do not have render props for classname, style and children

**Comment by victortrinh2** [comment]
There was 2 PRs for this:

- https://github.com/gsoft-inc/wl-hopper/pull/423
- https://github.com/gsoft-inc/wl-hopper/pull/424

Not sure if I missed any, so I didn't close it.
