### ISSUE TITLE
Modifying the syntax of collection components

### ISSUE THREAD

**Issue by franckgaudin** [gsoft-inc/wl-hopper#279]
To facilitate discovery and minimize the number of imports into applications, we should use this syntax for collection components. 

```
import {CheckboxGroup } from "@hopper-ui/components";

<CheckboxGroup>
  <CheckboxGroup.Label>
    Roles
  </CheckboxGroup.Label>
  <CheckboxGroup.List>
    <Checkbox value="developer">
      Developer
    </Checkbox>
     ....
  </CheckboxGroup.List >
  <CheckboxGroup.HelperMessage>
    Select one to continue
  </CheckboxGroup.HelperMessage>
</CheckboxGroup>
```

**Comment by vicky-comeau** [comment]
Do we have an example somewhere that shows how the exports are done?

Also, CheckboxGroup isn't a true collection, how do we know which to include?
Only ListBox at the moment is a true collection that uses RAC's Collection component.
Can we maybe list our current components that we want to see this done for?

**Comment by franckgaudin** [comment]
This point is still a little unclear to me and I think we should review it as a team. What I'm not sure about is whether we should do it only for collection components or for all components. 

Example with Inputs

```
<TextField type="email" placeholder="billings@acme.com" isRequired>
    <TextField.Label>Email adress</Label>
    <TextField.HelperMessage>Invoices will be sent to this email address.</HelperMessage>
</TextField>
```

Using this approach simplifies the discovery of the elements available to the component, thanks to autocompletion. On the other hand, if we use this approach everywhere, we move away from our architecture.

For exports, here is an example:

```
_ListBox.Item = ListBoxItem;

export { _ListBox as ListBox };
```
We'll certainly have to revise the types, but it would be something like this
