### ISSUE TITLE
Make sure every type from RAC that can be imported from Hopper.

### ISSUE THREAD

**Issue by alexasselin008** [gsoft-inc/wl-hopper#282]
A lot of types from RAC are used by our components. For instance, the type "Key", "Orientation", "SortDirection". We should make sure that inside the index.ts of hopper, we re-export those typings.

We could probably create a script that ensures that every types extracted from our component props are listed and exported from our index.ts file. 

//index.ts
```
export { Key, Orientation, SortDirection } from "react-aria-components";
```

Expected Outcome

```
import { Select, Key } from "@hopper-ui/components"
...

const handleChange = (k: Key) => { 
   console.log(k);
}
...

<Select onChange={handleChange} >

```

**Comment by vicky-comeau** [comment]
Done
