### ISSUE TITLE
[Add Token] Add --hop-space-10 token of value 0.0625rem

### ISSUE THREAD

**Issue by JeffreyLYT** [gsoft-inc/wl-hopper#349]
Now that we have rebranded to WL and are now base 16 for rem values, there seems to be many instances where borders of 1px are set to 0.0625rem. It might be worth creating a semantic token to represent this value, something like `--hop-space-10`?

https://hopper.workleap.design/tokens/core/dimensions#tokens

**Comment by fraincs** [comment]
Thanks for the feedback, this token will be added as a core token.  A semantic token would require a meaning, such as border-thin, border-thick.

**Comment by fraincs** [comment]
@JeffreyLYT the token has been added.
