### ISSUE TITLE
Simplify import of css files for components

### ISSUE THREAD

**Issue by franckgaudin** [gsoft-inc/wl-hopper#361]
When using the `@hopper-ui/components` library, you need to install several css files found in other libraries. We could simplify this approach by including them in the `index.css` file.

### Currently
```
@import "@hopper-ui/components/index.css";
@import "@hopper-ui/icons/index.css";
@import "@hopper-ui/tokens/fonts.css";
@import "@hopper-ui/styled-system/index.css";
```

### Expected
```
@import "@hopper-ui/components/index.css";
```

**Comment by vicky-comeau** [comment]
Would it actually be within the components folder? or should it be @hopper-ui/index.css?

**Comment by franckgaudin** [comment]
It's located in the components folder, and the problem is that this file is automatically generated during the build process. It will gather all component css and aggregate them in this file. My initial research showed that to modify it, you'd need to create a cssModule plugin to inject the necessary imports.

**Comment by vicky-comeau** [comment]
this is done.
