### ISSUE TITLE
Label required logic

### ISSUE THREAD

**Issue by franckgaudin** [gsoft-inc/wl-hopper#384]
We've had this discussion a while back with some developers that needed a way to invert the required logic, or not show the '*' if a field is required.

Two scenarios that I think we don't cover:

- All fields are required therefore showing a * everywhere can be intimidating, and prevent form submission as a user can drop the flow. A form footnote stating that all fields are required would be less intrusive.
- Most fields are required, we wanna only display a (optional) next to the non required fields.

_Originally posted by @fraincs in https://github.com/gsoft-inc/wl-hopper/issues/376#issuecomment-2263472960_

**Comment by vicky-comeau** [comment]
Completed
