### ISSUE TITLE
Add data visualization tokens

### ISSUE THREAD

**Issue by vicky-comeau** [gsoft-inc/wl-hopper#53]
We are missing the data viz tokens that can be found here: https://www.figma.com/file/he7mOkVFtqk0m3dgWKLcXk/%F0%9F%90%B8-Data-visualization?type=design&node-id=40%3A1101&mode=design&t=xN4wEHehbZ3UPWEg-1

**Comment by fraincs** [comment]
@franckgaudin is there a reason we don't have these as tokens?

**Comment by franckgaudin** [comment]
This was not a priority at the time the library was created, as components with these tokens will arrive later. 
If the team load allows, we can add them.
