### ISSUE TITLE
Spacing variable for hop-space-640 does not follow the same standard as other space variables

### ISSUE THREAD

**Issue by cloutierlp** [gsoft-inc/wl-hopper#64]
I randomly discovered that using the `var(--hop-space-640)` wasn't working the same way as other `space` variables.

There seems to be a different strategy used to declare this value. It seems like a small error to me, but I prefer to open issue to open a discussion about it.

When I look at the token file it's the only value in "number" rather than "size"

https://github.com/gsoft-inc/wl-hopper/blob/18b2c36ef2f732354578c6038024c5213ed6b551/apps/docs/datas/tokens.json#L755-L760

Resulting in the following variables:

```
   --hop-space-1280: 8rem;
   --hop-space-960: 6rem;
   --hop-space-800: 5rem;
   --hop-space-640: 64; <---------------
   --hop-space-480: 3rem;
   --hop-space-400: 2.5rem;
   --hop-space-320: 2rem;
   --hop-space-240: 1.5rem;
   --hop-space-160: 1rem;
```

Is there a usecase that I don't have in mind or is it just not the desired value?

**Comment by fraincs** [comment]
Fixed in @hopper-ui/tokens@1.0.1
